// Code generated by MockGen. DO NOT EDIT.
// Source: authenticator.go

// Package mock_authenticator is a generated GoMock package.
package authenticator

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	account "github.com/samverrall/sitesmiths-api/account"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// GetDetailsFromToken mocks base method.
func (m *MockAuthenticator) GetDetailsFromToken(ctx context.Context, token Token) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailsFromToken", ctx, token)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailsFromToken indicates an expected call of GetDetailsFromToken.
func (mr *MockAuthenticatorMockRecorder) GetDetailsFromToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailsFromToken", reflect.TypeOf((*MockAuthenticator)(nil).GetDetailsFromToken), ctx, token)
}

// GetTokenFromCode mocks base method.
func (m *MockAuthenticator) GetTokenFromCode(ctx context.Context, code AuthCode) (Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenFromCode", ctx, code)
	ret0, _ := ret[0].(Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenFromCode indicates an expected call of GetTokenFromCode.
func (mr *MockAuthenticatorMockRecorder) GetTokenFromCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenFromCode", reflect.TypeOf((*MockAuthenticator)(nil).GetTokenFromCode), ctx, code)
}
